// Generated by CoffeeScript 1.6.3
var AutomationServer,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

AutomationServer = (function() {
  function AutomationServer(serverURL) {
    this.serverURL = serverURL;
    this.executeCommand = __bind(this.executeCommand, this);
    this.ACTIONS_URI = this.serverURL + "/actions";
    this.EXEC_URI = this.serverURL + "/exec";
  }

  AutomationServer.prototype.setReadyCallback = function(readyCallback) {
    this.readyCallback = readyCallback;
  };

  AutomationServer.prototype.getActionGroups = function() {
    var _this = this;
    return $.ajax(this.ACTIONS_URI, {
      type: "GET",
      dataType: "json",
      success: function(data, textStatus, jqXHR) {
        return _this.readyCallback(data);
      },
      error: function(jqXHR, textStatus, errorThrown) {
        return console.log("Get Actions failed: " + textStatus + " " + errorThrown);
      }
    });
  };

  AutomationServer.prototype.executeCommand = function(cmdParams) {
    var _this = this;
    return $.ajax(this.EXEC_URI + "/" + cmdParams, {
      type: "GET",
      dataType: "text",
      success: function(data, textStatus, jqXHR) {},
      error: function(jqXHR, textStatus, errorThrown) {
        return console.log("Exec command failed: " + textStatus + " " + errorThrown);
      }
    });
  };

  return AutomationServer;

})();
