// Generated by CoffeeScript 1.6.3
var SceneButton,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

SceneButton = (function(_super) {
  __extends(SceneButton, _super);

  function SceneButton(bkColour, colSpan, clickFn, clickParam, tileName, iconType, buttonText) {
    this.iconType = iconType;
    this.buttonText = buttonText;
    SceneButton.__super__.constructor.call(this, bkColour, colSpan, clickFn, clickParam, tileName);
  }

  SceneButton.prototype.addToDoc = function(elemToAddTo) {
    SceneButton.__super__.addToDoc.call(this);
    this.contents.append("<div class=\"sqSceneButtonIcon\"><img src=\"img/light-bulb-on.png\"></img></div>\n<div class=\"sqSceneButtonText\"></div>");
    if (this.buttonText.toLowerCase().indexOf("off") >= 0) {
      this.iconType = "bulb-off";
    } else if (this.buttonText.toLowerCase().indexOf(" on") >= 0) {
      this.iconType = "bulb-on";
    }
    this.buttonText = this.buttonText.replace(" Lights", "");
    this.buttonText = this.buttonText.replace(" Light", "");
    this.setIcon(this.iconType);
    return this.setText(this.buttonText);
  };

  SceneButton.prototype.setIcon = function(iconType) {
    var iconUrl;
    this.iconType = iconType;
    if (iconType === 'bulb-on') {
      iconUrl = 'img/light-bulb-on.png';
    } else if (iconType === 'bulb-off') {
      iconUrl = 'img/light-bulb-off.png';
    }
    return $('#' + this.tileId + " .sqSceneButtonIcon img").attr("src", iconUrl);
  };

  SceneButton.prototype.setText = function(textStr) {
    this.textStr = textStr;
    return $('#' + this.tileId + " .sqSceneButtonText").html(textStr);
  };

  return SceneButton;

})(Tile);
