// Generated by CoffeeScript 1.6.3
var TabletConfig;

TabletConfig = (function() {
  function TabletConfig(configURL) {
    this.configURL = configURL;
  }

  TabletConfig.prototype.setReadyCallback = function(readyCallback) {
    this.readyCallback = readyCallback;
  };

  TabletConfig.prototype.initTabletConfig = function() {
    var _this = this;
    return $.ajax(this.configURL, {
      type: "GET",
      dataType: "text",
      crossDomain: true,
      success: function(data, textStatus, jqXHR) {
        var jsonData, jsonText;
        jsonText = jqXHR.responseText;
        jsonData = $.parseJSON(jsonText);
        return _this.readyCallback(jsonData);
      }
    });
  };

  return TabletConfig;

})();
