// Generated by CoffeeScript 1.6.3
var TileBasics;

TileBasics = (function() {
  function TileBasics(bkColour, colSpan, clickFn, clickParam, tileName, visibility) {
    this.bkColour = bkColour;
    this.colSpan = colSpan;
    this.clickFn = clickFn;
    this.clickParam = clickParam;
    this.tileName = tileName;
    this.visibility = visibility;
  }

  return TileBasics;

})();
