// Generated by CoffeeScript 1.6.3
var TileColours;

TileColours = (function() {
  function TileColours() {
    this.tileColours = ["#a20025", "#1ba1e2", "#d80073", "#741b47", "#a4c400", "#6a00ff", "#76608a", "#6d8764", "#aa00ff", "#647687", "#9900ff", "#2566c2", "#bf9000", "#00aba9", "#008a00", "#f0a30a", "#825a2c", "#0050ef"];
    this.curTileColour = 0;
  }

  TileColours.prototype.getNextColour = function() {
    var colour;
    colour = this.tileColours[this.curTileColour];
    this.curTileColour += 1;
    if (this.curTileColour >= this.tileColours.length) {
      this.curTileColour = 0;
    }
    return colour;
  };

  return TileColours;

})();
